import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import os from "node:os";
import {
  createSlice,
  getSlice,
  updateSlice,
  readSliceCounters,
  regenerateScopeMap,
} from "./slices.js";

describe("slice storage primitives", () => {
  let tmpDir: string;
  let projectDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "aihub-slices-"));
    projectDir = path.join(tmpDir, "PRO-238_auth-flow");
    await fs.mkdir(projectDir, { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("creates slices dir and counters on first create", async () => {
    const created = await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Auth flow",
    });

    expect(created.id).toBe("PRO-238-S01");
    await expect(
      fs.stat(path.join(projectDir, "slices", "PRO-238-S01"))
    ).resolves.toBeDefined();

    const counters = await readSliceCounters(projectDir);
    expect(counters.lastSliceId).toBe(1);

    const countersRaw = await fs.readFile(
      path.join(projectDir, ".meta", "counters.json"),
      "utf8"
    );
    expect(JSON.parse(countersRaw)).toEqual({ lastSliceId: 1 });
  });

  it("allocates IDs per-project and persists counter", async () => {
    const first = await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Auth",
    });
    const second = await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Settings",
    });

    expect(first.id).toBe("PRO-238-S01");
    expect(second.id).toBe("PRO-238-S02");
    expect((await readSliceCounters(projectDir)).lastSliceId).toBe(2);
  });

  it("round-trips frontmatter without loss on update", async () => {
    const created = await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Auth",
    });

    const escaped = "A \"quote\" with \\ slash and \n newline";
    const updated = await updateSlice(projectDir, created.id, {
      frontmatter: {
        blocked_by: ["PRO-238-S02"],
        extra_json: { nested: [1, "two", true] },
        extra_text: "hello",
        escaped_text: escaped,
        nullable: null,
        empty_list: [],
      },
      status: "in_progress",
    });

    expect(updated.frontmatter.blocked_by).toEqual(["PRO-238-S02"]);
    expect(updated.frontmatter.extra_text).toBe("hello");
    expect(updated.frontmatter.extra_json).toEqual({ nested: [1, "two", true] });
    expect(updated.frontmatter.escaped_text).toBe(escaped);
    expect(updated.frontmatter.nullable).toBeNull();
    expect(updated.frontmatter.empty_list).toEqual([]);
    expect(updated.frontmatter.status).toBe("in_progress");

    const reread = await getSlice(projectDir, created.id);
    expect(reread.frontmatter.blocked_by).toEqual(["PRO-238-S02"]);
    expect(reread.frontmatter.extra_text).toBe("hello");
    expect(reread.frontmatter.extra_json).toEqual({ nested: [1, "two", true] });
    expect(reread.frontmatter.escaped_text).toBe(escaped);
    expect(reread.frontmatter.nullable).toBeNull();
    expect(reread.frontmatter.empty_list).toEqual([]);

    const cleared = await updateSlice(projectDir, created.id, {
      frontmatter: { blocked_by: [] },
    });
    expect(cleared.frontmatter.blocked_by).toBeUndefined();
    const raw = await fs.readFile(
      path.join(projectDir, "slices", created.id, "README.md"),
      "utf8"
    );
    expect(raw).not.toContain("blocked_by");
  });

  it("regenerates empty scope map", async () => {
    await regenerateScopeMap(projectDir, "PRO-238");

    const scopeMap = await fs.readFile(path.join(projectDir, "SCOPE_MAP.md"), "utf8");
    expect(scopeMap).toContain("# Scope map — PRO-238");
    expect(scopeMap).toContain("| Slice | Title | Status | Hill |");
    expect(scopeMap).not.toContain("PRO-238-S01");
  });

  it("regenerates scope map for single and multiple slices in deterministic id order", async () => {
    await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "First",
    });
    await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Second",
    });

    const scopeMap = await fs.readFile(path.join(projectDir, "SCOPE_MAP.md"), "utf8");
    const first = scopeMap.indexOf("PRO-238-S01");
    const second = scopeMap.indexOf("PRO-238-S02");
    expect(first).toBeGreaterThan(-1);
    expect(second).toBeGreaterThan(-1);
    expect(first).toBeLessThan(second);
  });

  it("writes scope map atomically and leaves no temp file", async () => {
    await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Auth",
    });

    await regenerateScopeMap(projectDir, "PRO-238");

    const scopeMapPath = path.join(projectDir, "SCOPE_MAP.md");
    const raw = await fs.readFile(scopeMapPath, "utf8");
    expect(raw).toContain("<!-- Auto-generated by aihub. Do not edit by hand. -->");
    expect(raw).toContain("| PRO-238-S01 | Auth | todo | figuring |");

    const files = await fs.readdir(projectDir);
    expect(files.some((name) => name.includes("SCOPE_MAP.md") && name.includes(".tmp"))).toBe(false);
  });

  it("updates README atomically and no temp file left", async () => {
    const created = await createSlice(projectDir, {
      projectId: "PRO-238",
      title: "Auth",
    });

    await updateSlice(projectDir, created.id, { readme: "## Must\n- login\n" });

    const readmePath = path.join(projectDir, "slices", created.id, "README.md");
    const raw = await fs.readFile(readmePath, "utf8");
    expect(raw).toContain("## Must");

    const files = await fs.readdir(path.dirname(readmePath));
    expect(files.some((name) => name.includes(".tmp"))).toBe(false);
  });

  it("concurrent scope map regens serialize", async () => {
    await Promise.all(
      Array.from({ length: 4 }, (_, index) =>
        createSlice(projectDir, {
          projectId: "PRO-238",
          title: `Slice ${index + 1}`,
        })
      )
    );

    await Promise.all(
      Array.from({ length: 10 }, () => regenerateScopeMap(projectDir, "PRO-238"))
    );

    const scopeMap = await fs.readFile(path.join(projectDir, "SCOPE_MAP.md"), "utf8");
    expect(scopeMap).toContain("PRO-238-S01");
    expect(scopeMap).toContain("PRO-238-S04");
    expect(scopeMap).not.toContain("undefined");
  });

  it("concurrent creates do not collide", async () => {
    const results = await Promise.all(
      Array.from({ length: 12 }, (_, index) =>
        createSlice(projectDir, {
          projectId: "PRO-238",
          title: `Slice ${index + 1}`,
        })
      )
    );

    const ids = results.map((item) => item.id).sort();
    expect(new Set(ids).size).toBe(12);
    expect(ids[0]).toBe("PRO-238-S01");
    expect(ids[11]).toBe("PRO-238-S12");
    expect((await readSliceCounters(projectDir)).lastSliceId).toBe(12);
  });

  it("rejects invalid projectId before path joins", async () => {
    await expect(
      createSlice(projectDir, {
        projectId: "../PRO-238",
        title: "bad",
      })
    ).rejects.toThrow("Invalid projectId");

    await expect(
      createSlice(projectDir, {
        projectId: "PRO-abc",
        title: "bad",
      })
    ).rejects.toThrow("Invalid projectId");
  });

  it("rejects invalid sliceId before path joins", async () => {
    await expect(getSlice(projectDir, "../PRO-238-S01")).rejects.toThrow("Invalid sliceId");
    await expect(updateSlice(projectDir, "PRO-238/../S01", {})).rejects.toThrow("Invalid sliceId");
    await expect(getSlice(projectDir, "PRO-238-Sx1")).rejects.toThrow("Invalid sliceId");
  });
});
