import { describe, expect, it, vi } from "vitest";
import type { ExtensionContext, IrcExtensionConfig } from "@aihub/shared";
import { IrcRouter } from "./router.js";

const config: IrcExtensionConfig = { host: "localhost", port: 6667, tls: false, nick: "aihub", channels: { "#team": { agent: "main", mode: "mention-only" } }, dm: { enabled: true, agent: "main", allowFrom: ["alice"], debounceMs: 1 }, historyLimit: 3, maxA2ATurns: 2, humanNicks: ["alice"] };
function setup(payloads = [{ text: "**ok**" }], routerConfig: IrcExtensionConfig = config) { const runAgent = vi.fn().mockResolvedValue({ payloads, meta: { durationMs: 0, sessionId: "x" } }); const ctx = { getAgent: () => ({ id: "main", workspace: ".", extensions: { irc: { enabled: true } } }), getAgents: () => [], isAgentActive: () => true, runAgent } as unknown as ExtensionContext; const send = vi.fn(); return { ctx, router: new IrcRouter(ctx, routerConfig, { send, nick: "aihub" }), runAgent, send }; }
const message = (prefix: string, target: string, trailing: string) => ({ prefix, command: "PRIVMSG", params: [target], trailing });
describe("IRC router", () => {
  it("acks accepted channel messages before invoking the agent", () => { const { router, runAgent, send } = setup([]); router.handle(message("bob!u@h", "#team", "aihub: answer")); expect(send).toHaveBeenCalledWith("#team", "👀"); expect(send.mock.invocationCallOrder[0]).toBeLessThan(runAgent.mock.invocationCallOrder[0]); });
  it("acks reply-all channel messages without requiring a mention", () => { const { router, runAgent, send } = setup([], { ...config, channels: { "#team": { agent: "main", mode: "reply-all" } } }); router.handle(message("bob!u@h", "#team", "answer")); expect(send).toHaveBeenCalledWith("#team", "👀"); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "answer" })); });
  it("does not ack ignored, unaddressed, disallowed, or loop-guarded messages", () => { const { ctx, router, runAgent, send } = setup([]); router.handle(message("bob!u@h", "#team", "unaddressed")); router.handle(message("mallory!u@h", "aihub", "disallowed")); router.handle(message("aihub!u@h", "#team", "aihub: loop")); const guardedSend = vi.fn(); const guarded = new IrcRouter(ctx, { ...config, maxA2ATurns: 0, humanNicks: [] }, { send: guardedSend, nick: "aihub" }); const warn = vi.spyOn(console, "warn").mockImplementation(() => {}); try { guarded.handle(message("bob!u@h", "#team", "aihub: capped")); } finally { warn.mockRestore(); } expect(runAgent).not.toHaveBeenCalled(); expect(send).not.toHaveBeenCalled(); expect(guardedSend).not.toHaveBeenCalled(); });
  it("acks a debounced DM once when its coalesced run dispatches", async () => { vi.useFakeTimers(); try { const { router, runAgent, send } = setup([]); router.handle(message("alice!u@h", "aihub", "one")); router.handle(message("alice!u@h", "aihub", "two")); expect(send).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "one\ntwo", sessionKey: "irc:alice" })); expect(send.mock.calls.filter(([, text]) => text === "👀")).toEqual([["alice", "👀"]]); } finally { vi.useRealTimers(); } });
  it("uses ambient channel context and replies to nick-addressed messages", async () => { const { router, runAgent, send } = setup(); router.handle(message("bob!u@h", "#team", "unaddressed context")); router.handle(message("bob!u@h", "#team", "aihub: answer")); await new Promise((resolve) => setTimeout(resolve, 10)); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "answer", sessionKey: "irc:#team", context: expect.objectContaining({ kind: "irc" }) })); await new Promise((resolve) => setTimeout(resolve, 450)); expect(send).toHaveBeenCalledWith("#team", "ok"); });
  it("accepts explicit owner without legacy extension opt-in", async () => { const runAgent = vi.fn().mockResolvedValue({ payloads: [], meta: {} }); const ctx = { getAgent: () => ({ id: "main", workspace: "." }), isAgentActive: () => true, runAgent } as unknown as ExtensionContext; const router = new IrcRouter(ctx, config, { send: vi.fn(), nick: "aihub" }, "main"); router.handle(message("bob!u@h", "#team", "aihub: owned")); await new Promise((resolve) => setTimeout(resolve, 10)); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ agentId: "main", message: "owned" })); });
  it("requires explicit DM enablement and discards debounced work on stop", async () => { const { ctx, router, runAgent } = setup(); const disabled = new IrcRouter(ctx, { ...config, dm: undefined }, { send: vi.fn(), nick: "aihub" }); disabled.handle(message("alice!u@h", "aihub", "nope")); router.handle(message("alice!u@h", "aihub", "later")); router.stop(); await new Promise((resolve) => setTimeout(resolve, 20)); expect(runAgent).not.toHaveBeenCalled(); });
});
